name: release

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  tagged-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm ci
      - run: npm run package
      - uses: battila7/get-version-action@v2
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          files: psalm-vscode-plugin-${{ steps.get_version.outputs.version }}.vsix